import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

const ggSans = localFont({
  src: [
    {
      path: "./../../public/ggsansRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/ggsansMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/ggsansSemibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../../public/ggsansBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ggsans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={ggSans.className}
    >
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
